# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Business-OnlinePayment-ElavonVirtualMerchant
version:      0.01
version_from: ElavonVirtualMerchant.pm
installdirs:  site
requires:
    Business::OnlinePayment::viaKLIX: 

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
